# Generated by Django 5.1.6 on 2025-03-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_genre_song_uploaded_at_alter_song_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='music.artist'),
        ),
    ]
