# Generated by Django 5.1.6 on 2025-03-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_artist_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='covers/'),
        ),
    ]
